all:
#	g++ -g datatypes.cpp -o datatypes.out
#	g++ -g pointers.cpp -o pointers.out
	g++ -g -std=c++14 smartpointers.cpp -o smartpointers.out
	g++ -g -std=c++14 sort.cpp -o sort.out
	g++ -g -std=c++14 test1.cpp -o test1.out
	g++ -g -std=c++14 queue_ADT.cpp -o queue_ADT.out

